version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - 'redis:/data'
    ports:
      - "6379:6379"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daiphamblog
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
      REDIS_URL: redis://redis:6379/0
volumes:
  pgdata:
  redis:
networks:
  default:
    external:
      name: daiphamblog