version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: 'redis:5.0'
    command: redis-server
    volumes:
      - 'redis:/data'
    # ports:
    #   - '6379:6379'
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
      REDIS_URL: redis://redis:6379
  web:    
    build:      
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: daipham_blog
    ports:
      - '80:80'
      - '443:443'
    depends_on:      
      - app
volumes:
  pgdata:
  redis: