default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= Rails.application.credentials.db_pass %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: daiphamblog_development

test:
  <<: *default
  database: daiphamblog_test

production:
  <<: *default
  database: daiphamblog_production